#!/bin/bash

DIR="$(dirname "$(readlink -f "${0}")")"

if [[ "$(uname -m)" == "x86_64" || "$(uname -m)" =~ ^i[3-6]86$ ]]; then
    $DIR/Tools/7zz.i386 "$@"
elif [ "$(uname -m)" == "armv7l" ]; then
    $DIR/Tools/7zz.arm "$@"
elif [ "$(uname -m)" == "aarch64" ]; then
    $DIR/Tools/7zz.aarch64 "$@"
else
    echo -e "\e[31mE: Unknown Architecture: $(uname -m) from 7zip\e[0m" >&2
    exit 1
fi
